import 'package:hive/hive.dart';

part 'note_model.g.dart';

/// A rich-text note created by the user or generated by the AI brain-dump.
///
/// Stored in the Hive `notesBox` (typeId 1). Notes can be pinned to the
/// top of the list, tagged for filtering, and linked to [TaskItem]s.
@HiveType(typeId: 1)
class NoteItem extends HiveObject {
  /// Unique identifier (UUID v4).
  @HiveField(0)
  String id;

  /// Note title shown in list and editor header.
  @HiveField(1)
  String title;

  /// Full markdown-compatible body text.
  @HiveField(2)
  String content;

  /// AI-generated one-sentence summary; null until [AIService.summarizeNote] runs.
  @HiveField(3)
  String? summary;

  /// User-defined labels for filtering and AI context.
  @HiveField(4)
  List<String> tags;

  /// When this note was first created.
  @HiveField(5)
  DateTime createdAt;

  /// When this note was last edited.
  @HiveField(6)
  DateTime updatedAt;

  /// IDs of [TaskItem]s linked to this note.
  @HiveField(7)
  List<String> linkedTaskIds;

  /// Whether this note is pinned to the top of the notes list.
  @HiveField(8)
  bool isPinned;

  NoteItem({
    required this.id,
    required this.title,
    required this.content,
    this.summary,
    this.tags = const [],
    required this.createdAt,
    required this.updatedAt,
    this.linkedTaskIds = const [],
    this.isPinned = false,
  });

  /// Returns a new [NoteItem] with the given fields replaced.
  /// Fields not passed retain their current value.
  NoteItem copyWith({
    String? id,
    String? title,
    String? content,
    String? summary,
    List<String>? tags,
    DateTime? createdAt,
    DateTime? updatedAt,
    List<String>? linkedTaskIds,
    bool? isPinned,
  }) {
    return NoteItem(
      id: id ?? this.id,
      title: title ?? this.title,
      content: content ?? this.content,
      summary: summary ?? this.summary,
      tags: tags ?? this.tags,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      linkedTaskIds: linkedTaskIds ?? this.linkedTaskIds,
      isPinned: isPinned ?? this.isPinned,
    );
  }
}
